batch_size: 8
iters: 100000

model:
  type: ISNetDIS
  
train_dataset:
  type: DIS5K
  dataset_root: ./DIS5K/DIS-TR
  transforms:
    - type: RandomHorizontalFlip
    - type: Normalize
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 1.0, 1.0, 1.0 ]
  mode: train

val_dataset:
  type: DIS5K
  dataset_root: ./DIS5K/DIS-VD
  transforms:
    - type: Normalize
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 1.0, 1.0, 1.0 ]
  mode: val

loss:
  types:
    - type: muti_loss_fusion
  coef: [1]
